# .streamlit/secrets.toml

# Application settings
[general]
app_name = "Community Hub"
admin_email = "aman@communityhub.com"
support_email = "support@communityhub.com"

# You can add external API keys here
[api_keys]
# Example: replace with actual keys when needed
# openai_api_key = "your-openai-key-here"
# sendgrid_api_key = "your-sendgrid-key-here"
# twilio_api_key = "your-twilio-key-here"

# Database credentials (if using external database)
[database]
# Example: replace with actual credentials when needed
# type = "postgresql"
# host = "localhost"
# port = "5432"
# username = "postgres"
# password = "your-password-here"
# database_name = "community_db"

# Email settings
[email]
# Example: replace with actual settings when needed
# smtp_server = "smtp.gmail.com"
# smtp_port = "587"
# smtp_username = "your-email@gmail.com"
# smtp_password = "your-app-password-here"

# Custom application settings
[app_settings]
developer = "Aman Jha"
version = "1.0.0"
build_date = "2025-05-12"